name: Veracode SCA Agent Demo
on: workflow_dispatch
    
jobs:
  SCA:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SCAN_DIR: "./app"
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Execute SCA Agent
        run: curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor
