name: Veracode SCA Agent Demo
on: workflow_dispatch:
jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SCAN_DIR: "./app"
      run: curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor
